---
dependencies:
  - supervisor
  - docker-kafkabroker
  - docker-python-coverage
  # hgweb_hosts is used to populate SSH host keys. We don't know these
  # until Docker containers have started, so make it empty.
  # Something similar applies to ZooKeeper and Kafka settings.
  - {
      role: hg-ssh,
      ldap_uri: 'ldap://ldap:389/',
      sshd_hg_port: 22,
      hgweb_hosts: [],
      kafka_broker_id: 1024,
      kafka_host_name: dummyhost,
      kafka_zookeeper_connect: dummyhostports,
      s3_endpoint_url: 'http://localhost:5001',
      sns_endpoint_url: 'http://localhost:5002',
      awsevents_access_key_id: docker_sns_access_key,
      awsevents_secret_access_key: docker_sns_secret_access_key,
      zk_servers: { localhost: dummy }
    }
