---
repos:

  buildbot-configs:
    path: "/repos/buildbot-configs"

  conduit:
    path: "/repos/conduit"

  build-buildbotcustom:
    path: "/repos/build-buildbotcustom"

  gecko:
    path: "/repos/mozreview-gecko"
    tree: "autoland"

  reviewboard:
    path: "/repos/reviewboard"

  version-control-tools:
    path: "/repos/version-control-tools"

  phabricator-qa-dev:
    path: "/repos/phabricator-qa-dev"

  phabricator-qa-stage:
    path: "/repos/phabricator-qa-stage"

  build-tools:
    path: "/repos/build-tools"
