---
- name: restart cgconfig
  service: name=cgconfig state=restarted

# Fails in Docker.
- name: restart nrpe
  service: name=nrpe
           state=restarted
  ignore_errors: True

# Fails in Docker.
- name: restart rsyslogd
  service: name=rsyslog state=restarted
  ignore_errors: True

- name: reread supervisor
  command: /usr/bin/supervisorctl reread
  ignore_errors: True
