---
- name: install supervisor config
  copy: src=supervisor-docker.conf
        dest=/etc/supervisor.d/docker.conf
        owner=root
        group=root
        mode=0644

- name: install Docker support scripts
  copy: src={{ item }} dest=/{{ item }} mode=0755
  with_items:
    - create-repo
    - kill-wsgi-procs
    - refresh
    - set-urls

- name: Install psutil
  pip: name=psutil

- name: Configure MozReview user
  ini_file: dest=/etc/mercurial/hgrc section={{ item.section }} option={{ item.option }} value="{{ item.value }}"
  with_items:
    - { section: reviewboard, option: username, value: mozreview }
    - { section: reviewboard, option: password, value: mrpassword }

- name: add LDAP settings file
  template: src=ldap.json.j2
            dest=/etc/mercurial/ldap.json
            owner=root
            group=root
            mode=0644
