---
- include: repos.yml
- include: packages.yml

- name: create autoland user
  become: true
  user: name=autoland
        shell=/bin/bash
        system=yes
        state=present

- name: chmod autoland home
  file: path=/home/autoland
        mode=0755

- include: ssh.yml

- name: create virtualenv for autoland
  include: ../../../tasks/virtualenv.yml
           venv=/home/autoland/autoland_venv
           requirements=../roles/autoland/files/requirements.txt

- name: set up version-control-tools repo
  become: true
  become_user: autoland
  hg: repo={{ vct_repo }}
      dest=/home/autoland/version-control-tools
      revision={{ rev }}
      force=yes
      purge=yes

# Ansible hg module fails to delete ignored files so we do that here
- name: delete ignored files from version-control-tools repo
  become: true
  become_user: autoland
  command: hg --config extensions.purge= -R /home/autoland/version-control-tools purge --all

- name: install autoland site hgrc
  copy: src=../files/autoland_hgrc
        dest=/home/autoland/.hgrc
        owner=autoland
        group=autoland
        mode=0644

- name: install config.json
  template: src=config.json.j2
            dest=/home/autoland/version-control-tools/autoland/autoland/config.json
            owner=autoland
            group=autoland
            mode=0600
  notify:
    - restart autoland

- name: link config.json
  file: src=/home/autoland/version-control-tools/autoland/autoland/config.json
        dest=/home/autoland/config.json
        owner=autoland
        group=autoland
        state=link

- name: set custom selinux rule for virtualenv
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/home/autoland/autoland_venv(/.*)?"

- name: apply selinux policy to virtualenv
  command: restorecon -Rv /home/autoland/autoland_venv/

- name: set custom selinux rule for autoland
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/home/autoland/version-control-tools/autoland/autoland(/.*)?"

- name: apply selinux policy to autoland
  command: restorecon -Rv /home/autoland/version-control-tools/autoland/autoland/

- name: set selinux to allow httpd connentions to rds
  command: setsebool -P httpd_can_network_connect_db 1

- name: install autoland service
  copy: dest=/etc/systemd/system/autoland.service
        src=../files/autoland.service
        mode=0664
  notify:
    - reload systemd

- name: enable autoland service
  service: name=autoland
           state=started
           enabled=yes

- name: setup main conf file
  copy: src=httpd.conf
        dest=/etc/httpd/conf/httpd.conf
  notify:
    - restart apache

- name: remove conf.d
  file: path=/etc/httpd/conf.d/
        state=absent

- name: install autoland site
  copy: src=../files/autoland_httpd.conf
        dest=/etc/httpd/conf/autoland.conf
  notify:
    - restart apache

- name: start apache
  service: name=httpd
           state=started
           enabled=yes

