---

- name: setup ssh dir
  file: path=/home/autoland/.ssh
        state=directory
        owner=autoland
        group=autoland
        mode=0700

- name: setup autoland ssh config
  template: src=ssh_config.j2
            dest=/home/autoland/.ssh/config
            owner=autoland
            group=autoland
            mode=0644

- name: install autoland private ssh keys
  copy: src=/opt/secrets/autoland/ssh/{{ secrets.ssh_key_name }}
        dest=/home/autoland/.ssh/
        owner=autoland
        group=autoland
        mode=0600
        remote_src=True

- name: install autoland public ssh keys
  copy: src=/opt/secrets/autoland/ssh/{{ secrets.ssh_key_name }}.pub
        dest=/home/autoland/.ssh/
        owner=autoland
        group=autoland
        mode=0644
        remote_src=True

- name: install system wide known_hosts
  copy: src=../files/known_hosts
        dest=/etc/ssh/ssh_known_hosts
        owner=root
        group=root
        mode=0644
