---
dependencies:
  - docker-kafkabroker
  # Docker startup routines plug in proper values for ZooKeeper and
  # Kafka settings.
  - { role: hg-web,
      mirror_source: "@mirror_source@",
      mirror_ssh_user: hg,
      wsgi_processes: 4,
      httpd_start_servers: 1,
      httpd_min_spare_servers: 1,
      httpd_max_spare_servers: 2,
      httpd_server_limit: 4,
      httpd_max_clients: 4,
      vct_node: "DOCKER",
      kafka_broker_id: 2014,
      kafka_host_name: dummyhost,
      kafka_zookeeper_connect: dummyhostports,
      zk_servers: { localhost: dummy },
    }
