---
- name: install supervisor config
  copy: src=supervisor-{{ item }}.conf
        dest=/etc/supervisor.d/{{ item }}.conf
        owner=root
        group=root
        mode=0644
  with_items:
    - docker
    - docker-kafkabroker

- name: install Docker support files
  copy: src={{ item }} dest=/{{ item }} owner=root group=root mode=0755
  with_items:
    - entrypoint.py
    - entrypoint-solo
    - set-mirror-key.py

- name: Install Mozilla IP Address Test Document
  copy: src=moz-ip-ranges.txt dest=/var/hg/moz-ip-ranges.txt owner=root group=root mode=0644

# We have an additional virtualenv in Docker to run moz.build info
# directly from hgweb without the secure execution environment we
# run in production. We do this because we can't execute the secure
# wrapper inside Docker because of limited privileges of Docker
# containers. This is unfortunate. But it's what we have to do for
# now.

- name: create virtualenv for moz.build info
  include: ../../../tasks/virtualenv.yml
           venv=/var/hg/venv_mozbuild
           requirements=../roles/docker-hg-web/files/requirements-mozbuild.txt

